apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dsds
  name: dsds
  labels:
    app: dsds
spec:
  selector:
    matchLabels:
      app: dsds
  template:
    metadata:
      labels:
        app: dsds
        name: dsds
    spec:
      containers:
        - name: dsds
          image: mahendraintelops/test-project-v1/dsds
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8080
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        