apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-service
  name: test-service
  labels:
    app: test-service
spec:
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
        name: test-service
    spec:
      containers:
        - name: test-service
          image: mahendraintelops/test-project-v1/test-service
          imagePullPolicy: Always
       
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        