apiVersion: v1
kind: Service
metadata:
  namespace: test-service
  labels:
    app: test-service
  name: test-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: test-service
  type: ClusterIP
