/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.6
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type UserAPI struct {
	// Post /v2/user
	// Create user
	CreateUser gin.HandlerFunc
	// Post /v2/user/createWithArray
	// Creates list of users with given input array
	CreateUsersWithArrayInput gin.HandlerFunc
	// Post /v2/user/createWithList
	// Creates list of users with given input array
	CreateUsersWithListInput gin.HandlerFunc
	// Delete /v2/user/:username
	// Delete user
	DeleteUser gin.HandlerFunc
	// Get /v2/user/:username
	// Get user by user name
	GetUserByName gin.HandlerFunc
	// Get /v2/user/login
	// Logs user into the system
	LoginUser gin.HandlerFunc
	// Get /v2/user/logout
	// Logs out current logged in user session
	LogoutUser gin.HandlerFunc
	// Put /v2/user/:username
	// Updated user
	UpdateUser gin.HandlerFunc
}
